### ISSUE TITLE
Versions such as `1` are excluded from major-version solver matrix

### ISSUE THREAD

**Issue by bergmark** [haskell-CI/hackage-matrix-builder#1]
![screen shot 2015-04-19 at 02 08 00](https://cloud.githubusercontent.com/assets/100681/7217633/f1baaf62-e638-11e4-8358-c7afda9542f9.png)

because the latest utf8-string has version `1` instead of `1.0.0` the wildcards `1.*` and `1.0.*` don't match. I'd suggest changing these constraints to be of the form `>= 1 && < 1.1` instead.

**Comment by hvr** [comment]
I know... I have been wondering whether it should be discouraged to use single-digit version numbers, as they don't work well with the `== 1.0.*` syntax and therefore pose a bit of a risk of unexpected behaviour if the user is not aware of the subtlety.

Fwiw, I've been unsure whether to add an additional row `>=1 && <1.1` (rather than just replacing the `1.0` row)

**Comment by hvr** [comment]
This bug doesn't apply anymore in the current UI as there's no major-version constrained overview table anymore
